version: '3'
services:
  domoticz:
    image: domoticz/domoticz
    container_name: domoticz
    ports:
      - "8080:8080"
    volumes:
      - ./domoticz-data:/opt/domoticz/userdata
    environment:
      - TZ=Europe/London
  nats:
    container_name: nats
    image: nats:scratch
    entrypoint: /nats-server
    command: --js --sd /data --config /conf/nats.conf
    ports:
      - 4222:4222
      - 1883:1883
    volumes:
      - ./nats-data:/data
      - ./nats-conf:/conf
